version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - backend5

  backend1:
    build: ./app
    environment:
      - INSTANCE_NAME=backend1

  backend2:
    build: ./app
    environment:
      - INSTANCE_NAME=backend2

  backend3:
    build: ./app
    environment:
      - INSTANCE_NAME=backend3

  backend4:
    build: ./app
    environment:
      - INSTANCE_NAME=backend4

  backend5:
    build: ./app
    environment:
      - INSTANCE_NAME=backend5
